#!/usr/bin/env php
<?php
use Illuminate\Foundation\Console\Kernel;

// Because laravel has a __ helper function, it's important we include the class.g file to ensure our __ is used.
require_once __DIR__ . '/gulliver/system/class.g.php';
require_once __DIR__ . '/bootstrap/autoload.php';
require_once __DIR__ . '/bootstrap/app.php';

$scriptDir = dirname(__FILE__).'/';

  define("PROCESSMAKER_PATH", $scriptDir);
  define("WORKFLOW_PATH", $scriptDir . 'workflow/');
  define("WORKFLOW_BIN_PATH", $scriptDir . 'workflow/engine/bin/');
  error_reporting(error_reporting() & ~E_DEPRECATED & ~E_STRICT);
  
  include WORKFLOW_BIN_PATH . '/cli.php';

