#!/usr/bin/env php
<?php

  $scriptDir = dirname(__FILE__).'/';

  define("PROCESSMAKER_PATH", $scriptDir);
  define("WORKFLOW_PATH", $scriptDir . 'workflow/');
  define("WORKFLOW_BIN_PATH", $scriptDir . 'workflow/engine/bin/');
  error_reporting(error_reporting() & ~E_DEPRECATED & ~E_STRICT);
  
  include WORKFLOW_BIN_PATH . '/cli.php';

