<?php 
  require_once PATH_TRUNK . 'gulliver/thirdparty/smarty/libs/Smarty.class.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlDocument.php'; 
  require_once PATH_TRUNK . 'gulliver/thirdparty/propel/Propel.php' ;
  require_once PATH_TRUNK . 'gulliver/thirdparty/creole/Creole.php' ;
  require_once PATH_TRUNK . 'workflow/engine/classes/class.xpdl.php'; 

  /** 
   * Generated by ProcessMaker Test Unit Generator on 2012-05-10 at 20:56:17.
  */ 

  class classXpdlTest extends PHPUnit_Framework_TestCase 
  { 
    /**
    * @covers Xpdl::createProcessFromDataXpdl
    * @todo   Implement testcreateProcessFromDataXpdl().
    */
    public function testcreateProcessFromDataXpdl() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createProcessFromDataXpdl', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::updateProcessFromDataXpdl
    * @todo   Implement testupdateProcessFromDataXpdl().
    */
    public function testupdateProcessFromDataXpdl() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'updateProcessFromDataXpdl', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createProcessFromDataPmxml
    * @todo   Implement testcreateProcessFromDataPmxml().
    */
    public function testcreateProcessFromDataPmxml() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createProcessFromDataPmxml', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createSubProcessFromDataXpdl
    * @todo   Implement testcreateSubProcessFromDataXpdl().
    */
    public function testcreateSubProcessFromDataXpdl() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createSubProcessFromDataXpdl', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::verifyTasks
    * @todo   Implement testverifyTasks().
    */
    public function testverifyTasks() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'verifyTasks', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createRouteRowsXpdl
    * @todo   Implement testcreateRouteRowsXpdl().
    */
    public function testcreateRouteRowsXpdl() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createRouteRowsXpdl', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createSubProcessRowsXpdl
    * @todo   Implement testcreateSubProcessRowsXpdl().
    */
    public function testcreateSubProcessRowsXpdl() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createSubProcessRowsXpdl', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::findIdTask
    * @todo   Implement testfindIdTask().
    */
    public function testfindIdTask() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'findIdTask', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::xmdlProcess
    * @todo   Implement testxmdlProcess().
    */
    public function testxmdlProcess() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'xmdlProcess', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createPool
    * @todo   Implement testcreatePool().
    */
    public function testcreatePool() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createPool', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createArtifacts
    * @todo   Implement testcreateArtifacts().
    */
    public function testcreateArtifacts() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createArtifacts', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createSubProcessesXpdl
    * @todo   Implement testcreateSubProcessesXpdl().
    */
    public function testcreateSubProcessesXpdl() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createSubProcessesXpdl', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createActivitiesXpdl
    * @todo   Implement testcreateActivitiesXpdl().
    */
    public function testcreateActivitiesXpdl() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createActivitiesXpdl', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createTransitionsXpdl
    * @todo   Implement testcreateTransitionsXpdl().
    */
    public function testcreateTransitionsXpdl() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createTransitionsXpdl', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::getProcessDataXpdl
    * @todo   Implement testgetProcessDataXpdl().
    */
    public function testgetProcessDataXpdl() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'getProcessDataXpdl', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::sortArray
    * @todo   Implement testsortArray().
    */
    public function testsortArray() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'sortArray', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::verifyRoutes
    * @todo   Implement testverifyRoutes().
    */
    public function testverifyRoutes() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'verifyRoutes', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createProcess
    * @todo   Implement testcreateProcess().
    */
    public function testcreateProcess() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createProcess', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createSubProcesses
    * @todo   Implement testcreateSubProcesses().
    */
    public function testcreateSubProcesses() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createSubProcesses', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createTask
    * @todo   Implement testcreateTask().
    */
    public function testcreateTask() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createTask', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createDataTask
    * @todo   Implement testcreateDataTask().
    */
    public function testcreateDataTask() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createDataTask', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createRoute
    * @todo   Implement testcreateRoute().
    */
    public function testcreateRoute() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createRoute', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createSubProcess
    * @todo   Implement testcreateSubProcess().
    */
    public function testcreateSubProcess() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createSubProcess', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createGateways
    * @todo   Implement testcreateGateways().
    */
    public function testcreateGateways() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createGateways', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createLanesPM
    * @todo   Implement testcreateLanesPM().
    */
    public function testcreateLanesPM() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createLanesPM', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createLanes
    * @todo   Implement testcreateLanes().
    */
    public function testcreateLanes() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createLanes', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createLanesNewPM
    * @todo   Implement testcreateLanesNewPM().
    */
    public function testcreateLanesNewPM() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createLanesNewPM', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createActivities
    * @todo   Implement testcreateActivities().
    */
    public function testcreateActivities() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createActivities', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createEventMessages
    * @todo   Implement testcreateEventMessages().
    */
    public function testcreateEventMessages() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createEventMessages', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createScheduler
    * @todo   Implement testcreateScheduler().
    */
    public function testcreateScheduler() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createScheduler', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::calculateTimeScheduler
    * @todo   Implement testcalculateTimeScheduler().
    */
    public function testcalculateTimeScheduler() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'calculateTimeScheduler', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createArrayScheduler
    * @todo   Implement testcreateArrayScheduler().
    */
    public function testcreateArrayScheduler() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createArrayScheduler', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createTransitions
    * @todo   Implement testcreateTransitions().
    */
    public function testcreateTransitions() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createTransitions', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createActivity
    * @todo   Implement testcreateActivity().
    */
    public function testcreateActivity() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createActivity', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createExtended
    * @todo   Implement testcreateExtended().
    */
    public function testcreateExtended() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createExtended', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::findCoordinates
    * @todo   Implement testfindCoordinates().
    */
    public function testfindCoordinates() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'findCoordinates', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::findCoordinatesTransition
    * @todo   Implement testfindCoordinatesTransition().
    */
    public function testfindCoordinatesTransition() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'findCoordinatesTransition', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createArrayRoutes
    * @todo   Implement testcreateArrayRoutes().
    */
    public function testcreateArrayRoutes() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createArrayRoutes', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::convertArrayEnd
    * @todo   Implement testconvertArrayEnd().
    */
    public function testconvertArrayEnd() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'convertArrayEnd', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createTransitionsPM
    * @todo   Implement testcreateTransitionsPM().
    */
    public function testcreateTransitionsPM() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createTransitionsPM', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::super_unique
    * @todo   Implement testsuper_unique().
    */
    public function testsuper_unique() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'super_unique', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createProcessPM
    * @todo   Implement testcreateProcessPM().
    */
    public function testcreateProcessPM() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createProcessPM', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::createSubProcessesPM
    * @todo   Implement testcreateSubProcessesPM().
    */
    public function testcreateSubProcessesPM() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'createSubProcessesPM', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Xpdl::saveWebEntry
    * @todo   Implement testsaveWebEntry().
    */
    public function testsaveWebEntry() 
    { 
        if (class_exists('Xpdl')) {
             $methods = get_class_methods( 'Xpdl');
            $this->assertTrue( in_array( 'saveWebEntry', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

  } 
