<?php 
  require_once PATH_TRUNK . 'gulliver/thirdparty/smarty/libs/Smarty.class.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlDocument.php'; 
  require_once PATH_TRUNK . 'gulliver/thirdparty/propel/Propel.php' ;
  require_once PATH_TRUNK . 'gulliver/thirdparty/creole/Creole.php' ;
  require_once PATH_TRUNK . 'workflow/engine/classes/class.wsResponse.php'; 

  /** 
   * Generated by ProcessMaker Test Unit Generator on 2012-05-10 at 20:56:17.
  */ 

  class classwsResponseTest extends PHPUnit_Framework_TestCase 
  { 
    /**
    * @covers wsResponse::__construct
    * @todo   Implement test__construct().
    */
    public function test__construct() 
    { 
        if (class_exists('wsResponse')) {
             $methods = get_class_methods( 'wsResponse');
            $this->assertTrue( in_array( '__construct', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers wsResponse::getPayloadString
    * @todo   Implement testgetPayloadString().
    */
    public function testgetPayloadString() 
    { 
        if (class_exists('wsResponse')) {
             $methods = get_class_methods( 'wsResponse');
            $this->assertTrue( in_array( 'getPayloadString', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers wsResponse::getPayloadArray
    * @todo   Implement testgetPayloadArray().
    */
    public function testgetPayloadArray() 
    { 
        if (class_exists('wsResponse')) {
             $methods = get_class_methods( 'wsResponse');
            $this->assertTrue( in_array( 'getPayloadArray', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

  } 
