<?php 
  require_once PATH_TRUNK . 'gulliver/thirdparty/smarty/libs/Smarty.class.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlDocument.php'; 
  require_once PATH_TRUNK . 'gulliver/thirdparty/propel/Propel.php' ;
  require_once PATH_TRUNK . 'gulliver/thirdparty/creole/Creole.php' ;
  require_once PATH_TRUNK . 'workflow/engine/classes/class.popupMenu.php'; 

  /** 
   * Generated by ProcessMaker Test Unit Generator on 2012-05-10 at 20:56:18.
  */ 

  class classXmlForm_Field_popupOptionTest extends PHPUnit_Framework_TestCase 
  { 
    /**
    * @covers XmlForm_Field_popupOption::getEvents
    * @todo   Implement testgetEvents().
    */
    public function testgetEvents() 
    { 
        if (class_exists('XmlForm_Field_popupOption')) {
             $methods = get_class_methods( 'XmlForm_Field_popupOption');
            $this->assertTrue( in_array( 'getEvents', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

  } 
