<?php 
  require_once PATH_TRUNK . 'gulliver/thirdparty/smarty/libs/Smarty.class.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlDocument.php'; 
  require_once PATH_TRUNK . 'gulliver/thirdparty/propel/Propel.php' ;
  require_once PATH_TRUNK . 'gulliver/thirdparty/creole/Creole.php' ;
  require_once PATH_TRUNK . 'workflow/engine/classes/class.pmDashlet.php'; 

  /** 
   * Generated by ProcessMaker Test Unit Generator on 2012-05-10 at 20:56:17.
  */ 

  class classPMDashletTest extends PHPUnit_Framework_TestCase 
  { 
    /**
    * @covers PMDashlet::getAdditionalFields
    * @todo   Implement testgetAdditionalFields().
    */
    public function testgetAdditionalFields() 
    { 
        if (class_exists('PMDashlet')) {
             $methods = get_class_methods( 'PMDashlet');
            $this->assertTrue( in_array( 'getAdditionalFields', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PMDashlet::setup
    * @todo   Implement testsetup().
    */
    public function testsetup() 
    { 
        if (class_exists('PMDashlet')) {
             $methods = get_class_methods( 'PMDashlet');
            $this->assertTrue( in_array( 'setup', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PMDashlet::render
    * @todo   Implement testrender().
    */
    public function testrender() 
    { 
        if (class_exists('PMDashlet')) {
             $methods = get_class_methods( 'PMDashlet');
            $this->assertTrue( in_array( 'render', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PMDashlet::getDashletInstance
    * @todo   Implement testgetDashletInstance().
    */
    public function testgetDashletInstance() 
    { 
        if (class_exists('PMDashlet')) {
             $methods = get_class_methods( 'PMDashlet');
            $this->assertTrue( in_array( 'getDashletInstance', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PMDashlet::getDashletObject
    * @todo   Implement testgetDashletObject().
    */
    public function testgetDashletObject() 
    { 
        if (class_exists('PMDashlet')) {
             $methods = get_class_methods( 'PMDashlet');
            $this->assertTrue( in_array( 'getDashletObject', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PMDashlet::getDashletsInstances
    * @todo   Implement testgetDashletsInstances().
    */
    public function testgetDashletsInstances() 
    { 
        if (class_exists('PMDashlet')) {
             $methods = get_class_methods( 'PMDashlet');
            $this->assertTrue( in_array( 'getDashletsInstances', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PMDashlet::getDashletsInstancesQuantity
    * @todo   Implement testgetDashletsInstancesQuantity().
    */
    public function testgetDashletsInstancesQuantity() 
    { 
        if (class_exists('PMDashlet')) {
             $methods = get_class_methods( 'PMDashlet');
            $this->assertTrue( in_array( 'getDashletsInstancesQuantity', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PMDashlet::loadDashletInstance
    * @todo   Implement testloadDashletInstance().
    */
    public function testloadDashletInstance() 
    { 
        if (class_exists('PMDashlet')) {
             $methods = get_class_methods( 'PMDashlet');
            $this->assertTrue( in_array( 'loadDashletInstance', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PMDashlet::saveDashletInstance
    * @todo   Implement testsaveDashletInstance().
    */
    public function testsaveDashletInstance() 
    { 
        if (class_exists('PMDashlet')) {
             $methods = get_class_methods( 'PMDashlet');
            $this->assertTrue( in_array( 'saveDashletInstance', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PMDashlet::deleteDashletInstance
    * @todo   Implement testdeleteDashletInstance().
    */
    public function testdeleteDashletInstance() 
    { 
        if (class_exists('PMDashlet')) {
             $methods = get_class_methods( 'PMDashlet');
            $this->assertTrue( in_array( 'deleteDashletInstance', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PMDashlet::getDashletsInstancesForUser
    * @todo   Implement testgetDashletsInstancesForUser().
    */
    public function testgetDashletsInstancesForUser() 
    { 
        if (class_exists('PMDashlet')) {
             $methods = get_class_methods( 'PMDashlet');
            $this->assertTrue( in_array( 'getDashletsInstancesForUser', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PMDashlet::getXTemplate
    * @todo   Implement testgetXTemplate().
    */
    public function testgetXTemplate() 
    { 
        if (class_exists('PMDashlet')) {
             $methods = get_class_methods( 'PMDashlet');
            $this->assertTrue( in_array( 'getXTemplate', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PMDashlet::setIncludePath
    * @todo   Implement testsetIncludePath().
    */
    public function testsetIncludePath() 
    { 
        if (class_exists('PMDashlet')) {
             $methods = get_class_methods( 'PMDashlet');
            $this->assertTrue( in_array( 'setIncludePath', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

  } 
