<?php
require_once PATH_TRUNK . 'gulliver/thirdparty/smarty/libs/Smarty.class.php';
require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php';
require_once PATH_TRUNK . 'gulliver/system/class.xmlDocument.php';
require_once PATH_TRUNK . 'gulliver/system/class.form.php';
require_once PATH_TRUNK . 'gulliver/system/class.dbconnection.php';
require_once PATH_TRUNK . 'gulliver/thirdparty/propel/Propel.php';
require_once PATH_TRUNK . 'gulliver/thirdparty/creole/Creole.php';
require_once PATH_TRUNK . 'gulliver/thirdparty/pear/PEAR.php';
require_once PATH_TRUNK . 'workflow/engine/classes/class.archive.php';

/**
 * Generated by ProcessMaker Test Unit Generator on 2012-07-12 at 22:32:30.
*/

class classtar_fileTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var tar_file
    */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
    */
    protected function setUp()
    {
        $this->object = new tar_file('name');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
    */
    protected function tearDown()
    {
    }

    /**
     * This is the default method to test, if the class still having 
     * the same number of methods.
    */
    public function testNumberOfMethodsInThisClass()
    {
        $methods = get_class_methods('tar_file');
        $this->assertTrue( count($methods) == 16);
    }

    /**
    * @covers tar_file::tar_file
    * @todo   Implement testtar_file().
    */
    public function testtar_file()
    {
        $methods = get_class_methods($this->object);
        $this->assertTrue( in_array('tar_file', $methods ), 'exists method tar_file' );
        $r = new ReflectionMethod('tar_file', 'tar_file');
        $params = $r->getParameters();
        $this->assertTrue( $params[0]->getName() == 'name');
        $this->assertTrue( $params[0]->isArray() == false);
        $this->assertTrue( $params[0]->isOptional () == false);
    }

    /**
    * @covers tar_file::create_tar
    * @todo   Implement testcreate_tar().
    */
    public function testcreate_tar()
    {
        $methods = get_class_methods($this->object);
        $this->assertTrue( in_array('create_tar', $methods ), 'exists method create_tar' );
        $r = new ReflectionMethod('tar_file', 'create_tar');
        $params = $r->getParameters();
    }

    /**
    * @covers tar_file::extract_files
    * @todo   Implement testextract_files().
    */
    public function testextract_files()
    {
        $methods = get_class_methods($this->object);
        $this->assertTrue( in_array('extract_files', $methods ), 'exists method extract_files' );
        $r = new ReflectionMethod('tar_file', 'extract_files');
        $params = $r->getParameters();
    }

    /**
    * @covers tar_file::open_archive
    * @todo   Implement testopen_archive().
    */
    public function testopen_archive()
    {
        $methods = get_class_methods($this->object);
        $this->assertTrue( in_array('open_archive', $methods ), 'exists method open_archive' );
        $r = new ReflectionMethod('tar_file', 'open_archive');
        $params = $r->getParameters();
    }
}

