<?php 
  require_once PATH_TRUNK . 'gulliver/thirdparty/smarty/libs/Smarty.class.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlDocument.php'; 
  require_once PATH_TRUNK . 'gulliver/thirdparty/propel/Propel.php' ;
  require_once PATH_TRUNK . 'gulliver/thirdparty/creole/Creole.php' ;
  require_once PATH_TRUNK . 'workflow/engine/classes/class.pmPhing.php'; 

  /** 
   * Generated by ProcessMaker Test Unit Generator on 2012-05-10 at 20:56:12.
  */ 

  class classpmPhingTest extends PHPUnit_Framework_TestCase 
  { 
    /**
    * @covers pmPhing::getPhingVersion
    * @todo   Implement testgetPhingVersion().
    */
    public function testgetPhingVersion() 
    { 
        if (class_exists('pmPhing')) {
             $methods = get_class_methods( 'pmPhing');
            $this->assertTrue( in_array( 'getPhingVersion', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

  } 
