<?php
require_once PATH_TRUNK . 'gulliver/thirdparty/smarty/libs/Smarty.class.php';
require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php';
require_once PATH_TRUNK . 'gulliver/system/class.xmlDocument.php';
require_once PATH_TRUNK . 'gulliver/system/class.form.php';
require_once PATH_TRUNK . 'gulliver/system/class.dbconnection.php';
require_once PATH_TRUNK . 'gulliver/thirdparty/propel/Propel.php';
require_once PATH_TRUNK . 'gulliver/thirdparty/creole/Creole.php';
require_once PATH_TRUNK . 'gulliver/thirdparty/pear/PEAR.php';
require_once PATH_TRUNK . 'workflow/engine/classes/class.pmPhing.php';

/**
 * Generated by ProcessMaker Test Unit Generator on 2012-07-12 at 22:32:25.
*/

class classpmPhingTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var pmPhing
    */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
    */
    protected function setUp()
    {
        $this->object = new pmPhing();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
    */
    protected function tearDown()
    {
    }

    /**
     * This is the default method to test, if the class still having 
     * the same number of methods.
    */
    public function testNumberOfMethodsInThisClass()
    {
        $methods = get_class_methods('pmPhing');        $this->assertTrue( count($methods) == 35);
    }

    /**
    * @covers pmPhing::getPhingVersion
    * @todo   Implement testgetPhingVersion().
    */
    public function testgetPhingVersion()
    {
        $methods = get_class_methods($this->object);
        $this->assertTrue( in_array('getPhingVersion', $methods ), 'exists method getPhingVersion' );
        $r = new ReflectionMethod('pmPhing', 'getPhingVersion');
        $params = $r->getParameters();
    } 

  } 
