<?php 
  require_once PATH_TRUNK . 'gulliver/thirdparty/smarty/libs/Smarty.class.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlDocument.php'; 
  require_once PATH_TRUNK . 'gulliver/thirdparty/propel/Propel.php' ;
  require_once PATH_TRUNK . 'gulliver/thirdparty/creole/Creole.php' ;
  require_once PATH_TRUNK . 'workflow/engine/classes/class.dynaformEditor.php'; 

  /** 
   * Generated by ProcessMaker Test Unit Generator on 2012-05-10 at 20:56:17.
  */ 

  class classdynaformEditorTest extends PHPUnit_Framework_TestCase 
  { 
    /**
    * @covers dynaformEditor::dynaformEditor
    * @todo   Implement testdynaformEditor().
    */
    public function testdynaformEditor() 
    { 
        if (class_exists('dynaformEditor')) {
             $methods = get_class_methods( 'dynaformEditor');
            $this->assertTrue( in_array( 'dynaformEditor', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers dynaformEditor::_createDefaultXmlForm
    * @todo   Implement test_createDefaultXmlForm().
    */
    public function test_createDefaultXmlForm() 
    { 
        if (class_exists('dynaformEditor')) {
             $methods = get_class_methods( 'dynaformEditor');
            $this->assertTrue( in_array( '_createDefaultXmlForm', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers dynaformEditor::_render
    * @todo   Implement test_render().
    */
    public function test_render() 
    { 
        if (class_exists('dynaformEditor')) {
             $methods = get_class_methods( 'dynaformEditor');
            $this->assertTrue( in_array( '_render', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers dynaformEditor::_getFilename
    * @todo   Implement test_getFilename().
    */
    public function test_getFilename() 
    { 
        if (class_exists('dynaformEditor')) {
             $methods = get_class_methods( 'dynaformEditor');
            $this->assertTrue( in_array( '_getFilename', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers dynaformEditor::_setUseTemporalCopy
    * @todo   Implement test_setUseTemporalCopy().
    */
    public function test_setUseTemporalCopy() 
    { 
        if (class_exists('dynaformEditor')) {
             $methods = get_class_methods( 'dynaformEditor');
            $this->assertTrue( in_array( '_setUseTemporalCopy', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers dynaformEditor::_setTmpData
    * @todo   Implement test_setTmpData().
    */
    public function test_setTmpData() 
    { 
        if (class_exists('dynaformEditor')) {
             $methods = get_class_methods( 'dynaformEditor');
            $this->assertTrue( in_array( '_setTmpData', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers dynaformEditor::_getTmpData
    * @todo   Implement test_getTmpData().
    */
    public function test_getTmpData() 
    { 
        if (class_exists('dynaformEditor')) {
             $methods = get_class_methods( 'dynaformEditor');
            $this->assertTrue( in_array( '_getTmpData', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers dynaformEditor::_copyFile
    * @todo   Implement test_copyFile().
    */
    public function test_copyFile() 
    { 
        if (class_exists('dynaformEditor')) {
             $methods = get_class_methods( 'dynaformEditor');
            $this->assertTrue( in_array( '_copyFile', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

  } 
