<?php 
  require_once PATH_TRUNK . 'gulliver/thirdparty/smarty/libs/Smarty.class.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlDocument.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.unitTest.php'; 

  /** 
   * Generated by ProcessMaker Test Unit Generator on 2012-05-10 at 20:39:58.
  */ 

  class classunitTestTest extends PHPUnit_Framework_TestCase 
  { 
    /**
    * @covers unitTest::unitTest
    * @todo   Implement testunitTest().
    */
    public function testunitTest() 
    { 
        if (class_exists('unitTest')) {
             $methods = get_class_methods( 'unitTest');
            $this->assertTrue( in_array( 'unitTest', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers unitTest::load
    * @todo   Implement testload().
    */
    public function testload() 
    { 
        if (class_exists('unitTest')) {
             $methods = get_class_methods( 'unitTest');
            $this->assertTrue( in_array( 'load', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers unitTest::runSingle
    * @todo   Implement testrunSingle().
    */
    public function testrunSingle() 
    { 
        if (class_exists('unitTest')) {
             $methods = get_class_methods( 'unitTest');
            $this->assertTrue( in_array( 'runSingle', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers unitTest::runMultiple
    * @todo   Implement testrunMultiple().
    */
    public function testrunMultiple() 
    { 
        if (class_exists('unitTest')) {
             $methods = get_class_methods( 'unitTest');
            $this->assertTrue( in_array( 'runMultiple', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers unitTest::runAll
    * @todo   Implement testrunAll().
    */
    public function testrunAll() 
    { 
        if (class_exists('unitTest')) {
             $methods = get_class_methods( 'unitTest');
            $this->assertTrue( in_array( 'runAll', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers unitTest::sampleTestFunction
    * @todo   Implement testsampleTestFunction().
    */
    public function testsampleTestFunction() 
    { 
        if (class_exists('unitTest')) {
             $methods = get_class_methods( 'unitTest');
            $this->assertTrue( in_array( 'sampleTestFunction', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

  } 
