<?php 
  require_once PATH_TRUNK . 'gulliver/thirdparty/smarty/libs/Smarty.class.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlDocument.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.soapNtlm.php'; 

  /** 
   * Generated by ProcessMaker Test Unit Generator on 2012-05-10 at 20:39:55.
  */ 

  class classsoapNtlmTest extends PHPUnit_Framework_TestCase 
  { 
    /**
    * @covers soapNtlm::getuser
    * @todo   Implement testgetuser().
    */
    public function testgetuser() 
    { 
        if (class_exists('soapNtlm')) {
             $methods = get_class_methods( 'soapNtlm');
            $this->assertTrue( in_array( 'getuser', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers soapNtlm::getpassword
    * @todo   Implement testgetpassword().
    */
    public function testgetpassword() 
    { 
        if (class_exists('soapNtlm')) {
             $methods = get_class_methods( 'soapNtlm');
            $this->assertTrue( in_array( 'getpassword', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers soapNtlm::stream_open
    * @todo   Implement teststream_open().
    */
    public function teststream_open() 
    { 
        if (class_exists('soapNtlm')) {
             $methods = get_class_methods( 'soapNtlm');
            $this->assertTrue( in_array( 'stream_open', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers soapNtlm::stream_close
    * @todo   Implement teststream_close().
    */
    public function teststream_close() 
    { 
        if (class_exists('soapNtlm')) {
             $methods = get_class_methods( 'soapNtlm');
            $this->assertTrue( in_array( 'stream_close', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers soapNtlm::stream_read
    * @todo   Implement teststream_read().
    */
    public function teststream_read() 
    { 
        if (class_exists('soapNtlm')) {
             $methods = get_class_methods( 'soapNtlm');
            $this->assertTrue( in_array( 'stream_read', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers soapNtlm::stream_write
    * @todo   Implement teststream_write().
    */
    public function teststream_write() 
    { 
        if (class_exists('soapNtlm')) {
             $methods = get_class_methods( 'soapNtlm');
            $this->assertTrue( in_array( 'stream_write', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers soapNtlm::stream_eof
    * @todo   Implement teststream_eof().
    */
    public function teststream_eof() 
    { 
        if (class_exists('soapNtlm')) {
             $methods = get_class_methods( 'soapNtlm');
            $this->assertTrue( in_array( 'stream_eof', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers soapNtlm::stream_tell
    * @todo   Implement teststream_tell().
    */
    public function teststream_tell() 
    { 
        if (class_exists('soapNtlm')) {
             $methods = get_class_methods( 'soapNtlm');
            $this->assertTrue( in_array( 'stream_tell', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers soapNtlm::stream_flush
    * @todo   Implement teststream_flush().
    */
    public function teststream_flush() 
    { 
        if (class_exists('soapNtlm')) {
             $methods = get_class_methods( 'soapNtlm');
            $this->assertTrue( in_array( 'stream_flush', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers soapNtlm::stream_stat
    * @todo   Implement teststream_stat().
    */
    public function teststream_stat() 
    { 
        if (class_exists('soapNtlm')) {
             $methods = get_class_methods( 'soapNtlm');
            $this->assertTrue( in_array( 'stream_stat', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers soapNtlm::url_stat
    * @todo   Implement testurl_stat().
    */
    public function testurl_stat() 
    { 
        if (class_exists('soapNtlm')) {
             $methods = get_class_methods( 'soapNtlm');
            $this->assertTrue( in_array( 'url_stat', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers soapNtlm::createBuffer
    * @todo   Implement testcreateBuffer().
    */
    public function testcreateBuffer() 
    { 
        if (class_exists('soapNtlm')) {
             $methods = get_class_methods( 'soapNtlm');
            $this->assertTrue( in_array( 'createBuffer', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

  } 
