<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-17 at 18:07:43.
 */
class i18n_POTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var i18n_PO
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new i18n_PO;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers i18n_PO::buildInit
     * @todo   Implement testBuildInit().
     */
    public function testBuildInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers i18n_PO::readInit
     * @todo   Implement testReadInit().
     */
    public function testReadInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers i18n_PO::addHeader
     * @todo   Implement testAddHeader().
     */
    public function testAddHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers i18n_PO::addTranslatorComment
     * @todo   Implement testAddTranslatorComment().
     */
    public function testAddTranslatorComment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers i18n_PO::addExtractedComment
     * @todo   Implement testAddExtractedComment().
     */
    public function testAddExtractedComment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers i18n_PO::addReference
     * @todo   Implement testAddReference().
     */
    public function testAddReference()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers i18n_PO::addFlag
     * @todo   Implement testAddFlag().
     */
    public function testAddFlag()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers i18n_PO::addPreviousUntranslatedString
     * @todo   Implement testAddPreviousUntranslatedString().
     */
    public function testAddPreviousUntranslatedString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers i18n_PO::addTranslation
     * @todo   Implement testAddTranslation().
     */
    public function testAddTranslation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers i18n_PO::_writeLine
     * @todo   Implement test_writeLine().
     */
    public function test_writeLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers i18n_PO::_write
     * @todo   Implement test_write().
     */
    public function test_write()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers i18n_PO::prepare
     * @todo   Implement testPrepare().
     */
    public function testPrepare()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers i18n_PO::headerStroke
     * @todo   Implement testHeaderStroke().
     */
    public function testHeaderStroke()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers i18n_PO::getHeaders
     * @todo   Implement testGetHeaders().
     */
    public function testGetHeaders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers i18n_PO::getTranslation
     * @todo   Implement testGetTranslation().
     */
    public function testGetTranslation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers i18n_PO::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
