<?php 
  require_once PATH_TRUNK . 'gulliver/thirdparty/smarty/libs/Smarty.class.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlDocument.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.tree.php'; 

  /** 
   * Generated by ProcessMaker Test Unit Generator on 2012-05-10 at 20:39:56.
  */ 

  class classTreeTest extends PHPUnit_Framework_TestCase 
  { 
    /**
    * @covers Tree::Tree
    * @todo   Implement testTree().
    */
    public function testTree() 
    { 
        if (class_exists('Tree')) {
             $methods = get_class_methods( 'Tree');
            $this->assertTrue( in_array( 'Tree', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Tree::addChild
    * @todo   Implement testaddChild().
    */
    public function testaddChild() 
    { 
        if (class_exists('Tree')) {
             $methods = get_class_methods( 'Tree');
            $this->assertTrue( in_array( 'addChild', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Tree::printPlus
    * @todo   Implement testprintPlus().
    */
    public function testprintPlus() 
    { 
        if (class_exists('Tree')) {
             $methods = get_class_methods( 'Tree');
            $this->assertTrue( in_array( 'printPlus', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Tree::printLabel
    * @todo   Implement testprintLabel().
    */
    public function testprintLabel() 
    { 
        if (class_exists('Tree')) {
             $methods = get_class_methods( 'Tree');
            $this->assertTrue( in_array( 'printLabel', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Tree::printContent
    * @todo   Implement testprintContent().
    */
    public function testprintContent() 
    { 
        if (class_exists('Tree')) {
             $methods = get_class_methods( 'Tree');
            $this->assertTrue( in_array( 'printContent', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers Tree::render
    * @todo   Implement testrender().
    */
    public function testrender() 
    { 
        if (class_exists('Tree')) {
             $methods = get_class_methods( 'Tree');
            $this->assertTrue( in_array( 'render', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

  } 
