<?php 
  require_once PATH_TRUNK . 'gulliver/thirdparty/smarty/libs/Smarty.class.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlDocument.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.soapNtlm.php'; 

  /** 
   * Generated by ProcessMaker Test Unit Generator on 2012-05-10 at 20:39:55.
  */ 

  class classPMServiceProviderNTLMStreamTest extends PHPUnit_Framework_TestCase 
  { 
    /**
    * @covers PMServiceProviderNTLMStream::getuser
    * @todo   Implement testgetuser().
    */
    public function testgetuser() 
    { 
        if (class_exists('PMServiceProviderNTLMStream')) {
             $methods = get_class_methods( 'PMServiceProviderNTLMStream');
            $this->assertTrue( in_array( 'getuser', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PMServiceProviderNTLMStream::getpassword
    * @todo   Implement testgetpassword().
    */
    public function testgetpassword() 
    { 
        if (class_exists('PMServiceProviderNTLMStream')) {
             $methods = get_class_methods( 'PMServiceProviderNTLMStream');
            $this->assertTrue( in_array( 'getpassword', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PMServiceProviderNTLMStream::setAuthStream
    * @todo   Implement testsetAuthStream().
    */
    public function testsetAuthStream() 
    { 
        if (class_exists('PMServiceProviderNTLMStream')) {
             $methods = get_class_methods( 'PMServiceProviderNTLMStream');
            $this->assertTrue( in_array( 'setAuthStream', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

  } 
