<?php 
  require_once PATH_TRUNK . 'gulliver/thirdparty/smarty/libs/Smarty.class.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlDocument.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php'; 

  /** 
   * Generated by ProcessMaker Test Unit Generator on 2012-05-10 at 20:39:57.
  */ 

  class classXmlForm_Field_ImageTest extends PHPUnit_Framework_TestCase 
  { 
    /**
    * @covers XmlForm_Field_Image::render
    * @todo   Implement testrender().
    */
    public function testrender() 
    { 
        if (class_exists('XmlForm_Field_Image')) {
             $methods = get_class_methods( 'XmlForm_Field_Image');
            $this->assertTrue( in_array( 'render', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers XmlForm_Field_Image::masktophp
    * @todo   Implement testmasktophp().
    */
    public function testmasktophp() 
    { 
        if (class_exists('XmlForm_Field_Image')) {
             $methods = get_class_methods( 'XmlForm_Field_Image');
            $this->assertTrue( in_array( 'masktophp', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

  } 
