<?php 
  require_once PATH_TRUNK . 'gulliver/thirdparty/smarty/libs/Smarty.class.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlDocument.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlformExtension.php'; 

  /** 
   * Generated by ProcessMaker Test Unit Generator on 2012-05-10 at 20:39:58.
  */ 

  class classXmlForm_Field_DVEditorTest extends PHPUnit_Framework_TestCase 
  { 
    /**
    * @covers XmlForm_Field_DVEditor::render
    * @todo   Implement testrender().
    */
    public function testrender() 
    { 
        if (class_exists('XmlForm_Field_DVEditor')) {
             $methods = get_class_methods( 'XmlForm_Field_DVEditor');
            $this->assertTrue( in_array( 'render', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers XmlForm_Field_DVEditor::attachEvents
    * @todo   Implement testattachEvents().
    */
    public function testattachEvents() 
    { 
        if (class_exists('XmlForm_Field_DVEditor')) {
             $methods = get_class_methods( 'XmlForm_Field_DVEditor');
            $this->assertTrue( in_array( 'attachEvents', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

  } 
