<?php 
  require_once PATH_TRUNK . 'gulliver/thirdparty/smarty/libs/Smarty.class.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlDocument.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.phpSqlParser.php'; 

  /** 
   * Generated by ProcessMaker Test Unit Generator on 2012-05-10 at 20:39:56.
  */ 

  class classPHPSQLParserTest extends PHPUnit_Framework_TestCase 
  { 
    /**
    * @covers PHPSQLParser::__construct
    * @todo   Implement test__construct().
    */
    public function test__construct() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( '__construct', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PHPSQLParser::parse
    * @todo   Implement testparse().
    */
    public function testparse() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( 'parse', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PHPSQLParser::count_paren
    * @todo   Implement testcount_paren().
    */
    public function testcount_paren() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( 'count_paren', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PHPSQLParser::count_backtick
    * @todo   Implement testcount_backtick().
    */
    public function testcount_backtick() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( 'count_backtick', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PHPSQLParser::split_sql
    * @todo   Implement testsplit_sql().
    */
    public function testsplit_sql() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( 'split_sql', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PHPSQLParser::process_sql
    * @todo   Implement testprocess_sql().
    */
    public function testprocess_sql() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( 'process_sql', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PHPSQLParser::process_set_list
    * @todo   Implement testprocess_set_list().
    */
    public function testprocess_set_list() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( 'process_set_list', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PHPSQLParser::process_limit
    * @todo   Implement testprocess_limit().
    */
    public function testprocess_limit() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( 'process_limit', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PHPSQLParser::process_select
    * @todo   Implement testprocess_select().
    */
    public function testprocess_select() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( 'process_select', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PHPSQLParser::process_select_expr
    * @todo   Implement testprocess_select_expr().
    */
    public function testprocess_select_expr() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( 'process_select_expr', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PHPSQLParser::process_from
    * @todo   Implement testprocess_from().
    */
    public function testprocess_from() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( 'process_from', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PHPSQLParser::process_group
    * @todo   Implement testprocess_group().
    */
    public function testprocess_group() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( 'process_group', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PHPSQLParser::process_expr_list
    * @todo   Implement testprocess_expr_list().
    */
    public function testprocess_expr_list() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( 'process_expr_list', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PHPSQLParser::process_update
    * @todo   Implement testprocess_update().
    */
    public function testprocess_update() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( 'process_update', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PHPSQLParser::process_delete
    * @todo   Implement testprocess_delete().
    */
    public function testprocess_delete() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( 'process_delete', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PHPSQLParser::process_insert
    * @todo   Implement testprocess_insert().
    */
    public function testprocess_insert() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( 'process_insert', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers PHPSQLParser::load_reserved_words
    * @todo   Implement testload_reserved_words().
    */
    public function testload_reserved_words() 
    { 
        if (class_exists('PHPSQLParser')) {
             $methods = get_class_methods( 'PHPSQLParser');
            $this->assertTrue( in_array( 'load_reserved_words', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

  } 
