<?php 
  require_once PATH_TRUNK . 'gulliver/thirdparty/smarty/libs/Smarty.class.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlDocument.php'; 
  require_once PATH_TRUNK . 'gulliver/system/class.xmlform.php'; 

  /** 
   * Generated by ProcessMaker Test Unit Generator on 2012-05-10 at 20:39:57.
  */ 

  class classXmlForm_Field_DateTest extends PHPUnit_Framework_TestCase 
  { 
    /**
    * @covers XmlForm_Field_Date::verifyDateFormat
    * @todo   Implement testverifyDateFormat().
    */
    public function testverifyDateFormat() 
    { 
        if (class_exists('XmlForm_Field_Date')) {
             $methods = get_class_methods( 'XmlForm_Field_Date');
            $this->assertTrue( in_array( 'verifyDateFormat', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers XmlForm_Field_Date::isvalidBeforeFormat
    * @todo   Implement testisvalidBeforeFormat().
    */
    public function testisvalidBeforeFormat() 
    { 
        if (class_exists('XmlForm_Field_Date')) {
             $methods = get_class_methods( 'XmlForm_Field_Date');
            $this->assertTrue( in_array( 'isvalidBeforeFormat', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers XmlForm_Field_Date::calculateBeforeFormat
    * @todo   Implement testcalculateBeforeFormat().
    */
    public function testcalculateBeforeFormat() 
    { 
        if (class_exists('XmlForm_Field_Date')) {
             $methods = get_class_methods( 'XmlForm_Field_Date');
            $this->assertTrue( in_array( 'calculateBeforeFormat', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers XmlForm_Field_Date::render
    * @todo   Implement testrender().
    */
    public function testrender() 
    { 
        if (class_exists('XmlForm_Field_Date')) {
             $methods = get_class_methods( 'XmlForm_Field_Date');
            $this->assertTrue( in_array( 'render', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers XmlForm_Field_Date::renderGrid
    * @todo   Implement testrenderGrid().
    */
    public function testrenderGrid() 
    { 
        if (class_exists('XmlForm_Field_Date')) {
             $methods = get_class_methods( 'XmlForm_Field_Date');
            $this->assertTrue( in_array( 'renderGrid', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

    /**
    * @covers XmlForm_Field_Date::__draw_widget
    * @todo   Implement test__draw_widget().
    */
    public function test__draw_widget() 
    { 
        if (class_exists('XmlForm_Field_Date')) {
             $methods = get_class_methods( 'XmlForm_Field_Date');
            $this->assertTrue( in_array( '__draw_widget', $methods ), 'seems like this function is outside this class' ); 
        } 
    } 

  } 
